agent:
  episodes: 100
  num_sim: 500
  save_interval: 10
  anet:
    learning_rate: 0.01
    epochs: 1
    batch_size: 100
    optimizer: "adam"
    hidden_layers: [
      [64, "relu"],
      [32, "relu"]
    ]
