agent:
  episodes: 400
  fit_interval: 1
  num_sim: 1000
  dynamic_sim: false
  min_sim: 50
  save_interval: 50
  rbuf_size: 10000
  default_policy: "agent"
  epsilon: 1
  epsilon_decay: 0.95
  visualize_episode: false
  sigma: 1
  sigma_decay: 1
  sigma_delay: 20
  anet:
    file_path: "models/hex7/1000sims_1c_1epsilon"
    learning_rate: 0.01
    epochs: 1
    batch_size: 64
    optimizer: "adam"
    hidden_layers: [
      [512, "relu"],
    ]
  mcts:
    c: 1
    exp_prob: 1.0
  critic:
    optimizer: "adam"
    learning_rate: 0.01
    hidden_layers: [
      [128, "relu"]
    ]

game:
  name: "hex"
  params:
    board_size: 7
topp:
  enabled: true
  # params irrelevant if enabled is false
  include_uniform: true
  num_games_per_series: 50
  num_games_to_visualize_per_series: 2
