agent:
  episodes: 100
  num_sim: 1000
  save_interval: 10
  rbuf_size: 100
  anet:
    learning_rate: 0.01
    epochs: 1
    batch_size: 10
    optimizer: "adam"
    hidden_layers: [
      [32, "relu"],
    ]
  mcts:
    c: 1
    exp_prob: 1.0
