agent:
  episodes: 50
  num_sim: 200
  save_interval: 10
  rbuf_size: 100
  default_policy: "agent"
  dynamic_sim: false
  anet:
    learning_rate: 0.01
    epochs: 1
    batch_size: 10
    optimizer: "adam"
    hidden_layers: [
      [32, "relu"],
    ]
  mcts:
    c: 1
    exp_prob: 1.0
  oht:
    token: "34a2124a64b440c884577d4124acc784"
