agent:
  episodes: 300
  fit_interval: 1
  num_sim: 500
  dynamic_sim: false
  min_sim: 50
  save_interval: 50
  rbuf_size: 1024
  default_policy: "agent"
  epsilon: 0.2
  epsilon_decay: 0.98
  visualize_episode: false
  sigma: 1
  sigma_decay: 1
  sigma_delay: 20
  anet:
    weight_file: "rl/rl/models/anet_episode_299"
    learning_rate: 0.01
    epochs: 1
    batch_size: 64
    optimizer: "adam"
    hidden_layers: [
      [512, "relu"],
    ]
  mcts:
    c: 2
    exp_prob: 1.0
  critic:
    optimizer: "adam"
    learning_rate: 0.01
    hidden_layers: [
      [128, "relu"]
    ]

game:
  name: "hex"
  params:
    board_size: 7
topp:
  enabled: false
  # params irrelevant if enabled is false
  params:
    include_uniform: true
    num_games_per_series: 50