agent:
  anet:
    weight_file: "models/hex7/512relu_10000buf/anet_episode_250"
    optimizer: "adam"
    hidden_layers: [
      [ 512, "relu" ],
    ]
oht:
  token: ""
  qualify: false
  visualize: false
  league: true
