agent:
  anet:
    weight_file: "models/hex7/1000sims_1c_1epsilon/anet_episode_300"
    optimizer: "adam"
    hidden_layers: [
      [ 512, "relu" ],
    ]
oht:
  token: ""
  qualify: false
  visualize: false
  league: false
