agent:
  anet:
    hidden_layers: [
      [512, "relu"],
    ]
game:
  name: "hex"
  params:
    board_size: 5
topp:
  enabled: true
  # params irrelevant if enabled is false
  include_uniform: false
  num_games_per_series: 50
  weight_path: "models/hex5/512relu"
  num_games_to_visualize_per_series: 2